### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by hemanthdv** [vadimkantorov/cvpr2014#1]
## I am running into segmentation faults when I run the code on both Windows and Unix environments. Here is the output of a sample run:

xxxxxxxx$ ./fastvideofeat -i /Users/xxxxxx/DB/UCF11_updated_mpg/basketball/v_shooting_02/v_shooting_02_03.mpg > descriptors.txt
Options:
Input video: /Users/xxxxxx/DB/UCF11_updated_mpg/basketball/v_shooting_02/v_shooting_02_03.mpg
HOG's enabled: yes
HOF's enabled: yes
MBH's enabled: yes
Dense-dense-revolution: no
Interpolation: yes
Good PTS: 
Frame count:    144
Original frame size:    320x240
Downsampled:    20x15
After interpolation:    39x29
CellSize:   8
# read frame pts=45000
# skipping
# Frame number = 2
## Segmentation fault: 11

The segmentation fault appears to be originating from the frame_reader.h : line 359
bool good = USES_LIST(pFrame->mb_type[mb_index], direction);

Thank you for providing the code. Can you please help me resolve this issue.

**Comment by vadimkantorov** [comment]
Hi, I'm sorry for the enormous delay. Please let me know if you still have
the mentioned problems. I've updated the code recently.

2014-09-20 9:47 GMT+02:00 hemanthdv <notifications@github.com>:

> Thank you Vadim Katorov. That fixes the issue and I was able to test out
> both the programs (fastvideofeat and fisher fastfv). They work fine. The
> set of scripts were very helpful to understand how to use the code,
> especially the use of multiple options for fastfv. I however have a couple
> of questions.
>
>     1. Consider the hog component and the 1x1x1x grid. Since K=256, the fv for this supposed to be C.2DK = 1*2*96*256 = 49152. But when I extract the fisher vectors, I get a length of 96*256 = 24576. Similarly for the hof, I get a vector of length 108*256 = 27648 instead of 2*108*256 = 55296. Shouldn't we be considering both the first order(u) and second order(v) components for the fv.
>
>     2. The second question is related to the ttot option that is mandatory for fastfv. Can the 5th column of the last line in the descriptor file be used as the ttot value.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vadimkantorov/cvpr2014/issues/1#issuecomment-56259865>
> .
>



-- 
Vadim Kantorov
+33 6 03 29 27 69
