### ISSUE TITLE
Errors Creating Vocabulary

### ISSUE THREAD

**Issue by hemanthdv** [vadimkantorov/cvpr2014#2]
I am running into another error when I extract hof vocabulary. I am using descriptors from around 400 videos (around 2-3 million descriptors) to estimate the hof GMM vocabulary for fisher vectors. When I run the fastfv program with --buildGmmIndex option, I run into this problem.

$ cat vocabFileList.txt | xargs cat | ./fastfv --sigma yes --buildGmmIndex --vocab 105-212 hof_K256.vocab
​   :​
\# kmeans warning: 11 empty clusters -> split
   :
imfac = 6.665
keys    11: 2203.505343 -> 2194.710435
nb of 0 probabilities: 733755570 / (256*2889743) = 99.2 %
Assertion failed: (isfinite(fvec_sum(g->mu, k*d))), function gmm_compute_params, file gmm.c, line 218.
Abort trap: 6

I tried different sets of files as input but I get the same error. ​Can you please help me resolve this. Thank you for your help.

**Comment by vadimkantorov** [comment]
Hi,
Sorry for a huge delay. Please try now, I've updated the code and put a tested repro scripts.

**Comment by iammarvelous** [comment]
@vadimkantorov 
Hi, I met the same issue in [this line].(https://github.com/vadimkantorov/fastvideofeat/blob/master/src/gmm_train.py#L22).
Below is the error message. 
```
gmm.c:218: gmm_compute_params: Assertion `(sizeof (fvec_sum(g->mu, k*d)) == sizeof (float) ? __finitef (fvec_sum(g->mu, k*d)) : sizeof (fvec_sum(g->mu, k*d)) == sizeof (double) ? __finite (fvec_sum(g->mu, k*d)) : __finitel (fvec_sum(g->mu, k*d)))' failed.
```
The error always occurs on hof feature, which looks the same as this original post.
Do you have any ideas for fixing this?
