### ISSUE TITLE
Makefile needs to respect positional -L flags for systems that have OpenCV installed globally

### ISSUE THREAD

**Issue by brianthelion** [vadimkantorov/cvpr2014#4]
On systems that do _not_ have OpenCV installed globally, the current placement of the `-L` flags is fine. However, in the globally-installed case, the each `-L` flag needs to _immediately preceed_ the `-l` flags that reference it. Otherwise, the compiler will find the intended libraries on the system root rather than the depenedenices directory as intended.

This worked for me:

``` make
CFLAGS = -O3 -msse3 -std=c++0x
OPENCV_FLAGS = -I../../bin/dependencies/include -L../../bin/dependencies/lib -lopencv_flann -lopencv_core  -Wl,-Bdynamic -lpthread -lz -lm -lc -lrt
YAEL_FLAGS = -I../../bin/dependencies/yael -L../../bin/dependencies/yael/yael -lyael
LDFLAGS = -Wl,-Bstatic -lgomp -llapack -lf77blas -lcblas -latlas -lgfortran
BIN = ../../bin/fastfv

all: $(SOURCE_FILES)
    g++ main.cpp -o $(BIN) $(CFLAGS) $(LDFLAGS) $(OPENCV_FLAGS) $(YAEL_FLAGS)
clean:
    rm $(BIN)
```

**Comment by vadimkantorov** [comment]
Thanks for reporting this. I did a quick search online but couldn't find where this is specified or documented. Do you have pointers?

Should other dependencies (atlas, lapack, ...) also be preceded by corresponding -L? Should moving $(INSTALLED_DEPS) before $(LDFLAGS) also help?

**Comment by brianthelion** [comment]
Sorry, just saw this. I will track down a reference for you shortly.
