### ISSUE TITLE
MV vs RGB

### ISSUE THREAD

**Issue by kanzaali** [vadimkantorov/cvpr2014#5]
hi Vadim,

I want to understand how motion vectors are important features as compare to RGB information in video frames or what is complementary in MV as compare to RGB. Can you guide me how can I do this?

**Comment by vadimkantorov** [comment]
They are important if the motion of objects in scene is indicative of the action. Motion vectors are a crude approximation of optical flow. A priori, it is not guaranteed that optical flow is useful for your particular video task.

**Comment by kanzaali** [comment]
Hi Vadimkantorov,

Thank you so much for your valuable feedback.

I want to ask what is best method to compare RGB and motion vector?

I have calculated Action Recognition accuracy per class for UCF101 dataset
for RGB and motion vectors separately. What do you think about this
approach?

Regards,
Kanza

**Comment by vadimkantorov** [comment]
If you are interested in classification accuracy, you may be better off with more modern convnet-based methods
